<a href="https://colab.research.google.com/github/Kochristof/Python-Data-Science/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install nltk

In [13]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [1]:
# Defining a string variable containing the input text
text = "Natural Language Processing is awesome!"
 # Splitting the text into tokens (words) based on whitespace
tokens = text.split()
# Printing the resulting list of tokens
print(tokens)

# Output:
# ['Natural', 'Language', 'Processing', 'is', 'awesome!']

['Natural', 'Language', 'Processing', 'is', 'awesome!']


In [18]:
# Defining a string variable containing the input text
text = input()
 # Splitting the text into tokens (words) based on whitespace
tokens = text.split()
# Printing the resulting list of tokens
print(tokens)

Alasd
['Alasd']


In [19]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

 # Sample text
text = "This is a sample sentence demonstrating stopword removal."

# Creating a set of English stopwords
stop_words = set(stopwords.words('english'))

# Tokenizing the text into individual words
word_tokens = word_tokenize(text)

# Removing stopwords
filtered_text = [word for word in word_tokens if word.lower() not in stop_words]

# Printing the filtered text
print(filtered_text)


# Output: ['sample', 'sentence', 'demonstrating', 'stopword', 'removal', '.']

['sample', 'sentence', 'demonstrating', 'stopword', 'removal', '.']


In [21]:
# Importing the TfidfVectorizer class
from sklearn.feature_extraction.text import TfidfVectorizer

# Defining a corpus of text documents
corpus = input()

# Split the input into a list of strings
# This line is specific to the current snippet context and therefore may not appear elsewhere.
corpus = corpus.split(',')

# Initializing the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fitting the vectorizer to the corpus and transforming the corpus into a TF-IDF matrix
X = vectorizer.fit_transform(corpus)

# Printing the TF-IDF matrix in array format
print(X.toarray())

asddsa, asdas, asd 
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [11]:
# Assigning a string to the variable 'text'
text = "NLP is Amazing!"
# Converting the text to lowercase
normalized_text = text.lower()
# Printing the normalized text
print(normalized_text)


# Output: 'nlp is amazing!'

nlp is amazing!


In [22]:
# Assigning a string to the variable 'text'
text = input()
# Converting the text to lowercase
normalized_text = text.lower()
# Printing the normalized text
print(normalized_text)

asda 
asda 


In [14]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

# Initialize lemmatizer and stemmer
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

# Word to be processed
word = "running"

# Lemmatization
lemma_word = lemmatizer.lemmatize(word)

# Stemming
stem_word = stemmer.stem(word)


# Print results
print("Lemmatized Word:", lemma_word)
print("Stemmed Word:", stem_word)

# Output:
# Lemmatized Word: running
# Stemmed Word: run

Lemmatized Word: running
Stemmed Word: run


In [24]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

# Initialize lemmatizer and stemmer
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

# Word to be processed
word = input()

# Lemmatization
lemma_word = lemmatizer.lemmatize(word)

# Stemming
stem_word = stemmer.stem(word)


# Print results
print("Lemmatized Word:", lemma_word)
print("Stemmed Word:", stem_word)

sadas asd asdasd 
Lemmatized Word: sadas asd asdasd 
Stemmed Word: sadas asd asdasd 


In [15]:
import numpy as np

# List of words
words = ["apple", "banana", "orange", "grape"]

# Create a dictionary to map each word to an index
word_to_index = {word: i for i, word in enumerate(words)}

# Function to perform one-hot encoding
def one_hot_encoding(word, word_to_index):
    vector = np.zeros(len(word_to_index))
    vector[word_to_index[word]] = 1
    return vector

# Example usage
word = "banana"
encoded_vector = one_hot_encoding(word, word_to_index)

print("Word:", word)
print("One-Hot Encoded Vector:", encoded_vector)

Word: banana
One-Hot Encoded Vector: [0. 1. 0. 0.]


In [27]:
import numpy as np

# List of words
words = ["apple", "banana", "orange", "grape"]

# Create a dictionary to map each word to an index
word_to_index = {word: i for i, word in enumerate(words)}

# Function to perform one-hot encoding
def one_hot_encoding(word, word_to_index):
    vector = np.zeros(len(word_to_index))
    vector[word_to_index[word]] = 1
    return vector

# Example usage
word = input()
encoded_vector = one_hot_encoding(word, word_to_index)

print("Word:", word)
print("One-Hot Encoded Vector:", encoded_vector)

orange
Word: orange
One-Hot Encoded Vector: [0. 0. 1. 0.]


In [28]:
from nltk import ngrams # Importing the ngrams function from NLTK

# Defining a sample sentence
sentence = "The quick brown fox jumps over the lazy dog"
# Splitting the sentence into words
words = sentence.split()
# Generating a list of bigrams (2-grams) from the words
bigrams = list(ngrams(words, 2))
# Printing the list of bigrams
print(bigrams)


# Output:
#[('The', 'quick'), ('quick', 'brown'), ('brown', 'fox'), ('fox', 'jumps'), ('jumps', 'over'),
# ('over', 'the'), ('the', 'lazy'), ('lazy', 'dog')]

[('The', 'quick'), ('quick', 'brown'), ('brown', 'fox'), ('fox', 'jumps'), ('jumps', 'over'), ('over', 'the'), ('the', 'lazy'), ('lazy', 'dog')]


In [31]:
from nltk import ngrams # Importing the ngrams function from NLTK

# Defining a sample sentence
sentence = input()
# Splitting the sentence into words
words = sentence.split()
# Generating a list of bigrams (2-grams) from the words
bigrams = list(ngrams(words, 2))
# Printing the list of bigrams
print(bigrams)

aasda sadsdas asd asd asd 
[('aasda', 'sadsdas'), ('sadsdas', 'asd'), ('asd', 'asd'), ('asd', 'asd')]


In [32]:
# Importing the Counter class from the collections module
from collections import Counter

# Prompt the user to enter the text
corpus = input()

# Tokenize the input text into words
input_words = corpus.split()

# Calculate word frequencies
word_freq = Counter(input_words)

# Calculate word probabilities
total_words = sum(word_freq.values())
word_probs = {word: freq / total_words for word, freq in word_freq.items()}
print(word_probs)

asdasd asd as asd 
{'asdasd': 0.25, 'asd': 0.5, 'as': 0.25}


In [33]:
# Importing the TfidfVectorizer class
from sklearn.feature_extraction.text import TfidfVectorizer

# Defining a corpus of text documents
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

# Initializing the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fitting the vectorizer to the corpus and transforming the corpus into a TF-IDF matrix
X = vectorizer.fit_transform(corpus)

# Printing the TF-IDF matrix in array format
print(X.toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [35]:
 # Importing the Counter class from the collections module
from collections import Counter

# Prompt the user to enter the text
corpus = ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

# Calculate word frequencies
word_freq = Counter(corpus)

# Calculate word probabilities
total_words = sum(word_freq.values())
word_probs = {word: freq / total_words for word, freq in word_freq.items()}
print(word_probs)

{'the': 0.2222222222222222, 'quick': 0.1111111111111111, 'brown': 0.1111111111111111, 'fox': 0.1111111111111111, 'jumps': 0.1111111111111111, 'over': 0.1111111111111111, 'lazy': 0.1111111111111111, 'dog': 0.1111111111111111}


In [36]:
# Importing the spaCy library
import spacy

# Load the English NER model from spaCy
nlp = spacy.load("en_core_web_sm")

# Define the text containing named entities
text = "Apple is planning to build a new store in New York City."

# Process the text with the NER model
doc = nlp(text)

# Extract named entities from the processed text
entities = [(entity.text, entity.label_) for entity in doc.ents]

# Printing the extracted named entities and their labels
print(entities)

[('Apple', 'ORG'), ('New York City', 'GPE')]


In [37]:
# Importing the TextBlob class from the textblob library
from textblob import TextBlob

# Define the text for sentiment analysis
text = "I love this product! It's amazing."

# Create a TextBlob object with the input text
blob = TextBlob(text)

# Perform sentiment analysis Calculating the sentiment polarity score (-1 to 1)
sentiment_score = blob.sentiment.polarity

# Classify sentiment based on the sentiment score
if sentiment_score > 0:
    sentiment = "positive"
elif sentiment_score < 0:
    sentiment = "negative"
else:
    sentiment = "neutral"


# Print the sentiment classification
print("Sentiment:", sentiment)

Sentiment: positive
